table Fact_Sales
	lineageTag: 4fe505da-8ef5-42a5-aa47-87108470ab94

	measure 'Total Sales' =
			
			SUM(Fact_Sales[sales_amount])
		lineageTag: 6f66bde0-c0d1-48a2-a441-4000c13084cb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MoM Growth %' =
			
			VAR CurrentSales = [Total Sales]
			VAR PreviousSales =
			    CALCULATE(
			        [Total Sales],
			        DATEADD(Dim_Date[Date], -1, MONTH)
			    )
			RETURN
			    DIVIDE(CurrentSales - PreviousSales, PreviousSales)
		lineageTag: dacc1f59-8592-4507-8750-cf05b48a0a45

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Running Total Sales' =
			
			CALCULATE(
			    [Total Sales],
			    FILTER(
			        ALL(Dim_Date[Date]),
			        Dim_Date[Date] <= MAX(Dim_Date[Date])
			    )
			)
		lineageTag: 6421bf17-7029-4ccd-a230-ac9381c8ff60

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c19b9dc3-11ac-47cf-83b7-ab21f090b5c4
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column city
		dataType: string
		lineageTag: 144aa2b4-1a1c-42c8-8512-90a0be8afe8d
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column store_format
		dataType: string
		lineageTag: 697cf6f9-2c1a-4895-8d3d-bc2c51a123a5
		summarizeBy: none
		sourceColumn: store_format

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: be4b22b6-25b0-4516-bfc1-6769fdbef0a3
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: f7a9e0b6-ae61-462a-8060-003601fe70a4
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: 85a4b14f-a96b-469c-a79f-560c61eed3d1
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: int64
		formatString: 0
		lineageTag: d40bd29a-f011-432a-a65b-3e47fc2ca747
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column sales_amount
		dataType: double
		lineageTag: dc3ccaab-2717-4faa-b4c4-751bed111c2b
		summarizeBy: sum
		sourceColumn: sales_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_Sales = m
		mode: import
		source =
				let
				    Source = brewmetrics_sales,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"sale_id"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

